# Generated by Django 4.1.2 on 2022-10-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.BooleanField(default=True, null=True)),
                ('total_cars', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=60, null=True)),
                ('available_times', models.CharField(choices=[('Time1', '09:00 – 10:00'), ('Time2', '10:00 – 11:00'), ('Time3', '11:00 – 12:00'), ('Time4', '12:00 – 13:00'), ('Time5', '13:00 – 14:00'), ('Time6', '14:00 – 15:00'), ('Time7', '15:00 – 16:00'), ('Time8', '16:00 – 17:00')], max_length=250, verbose_name='Available Times')),
                ('parking', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='parking.parking')),
            ],
        ),
    ]
