# Generated by Django 4.1.2 on 2022-10-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_availabletimes_remove_reservation_available_times_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='status',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='parking',
            name='total_cars',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='available_times',
        ),
        migrations.AddField(
            model_name='reservation',
            name='resevation_time',
            field=models.TimeField(blank=True, max_length=255, null=True),
        ),
    ]
