# Generated by Django 4.1.2 on 2022-10-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_rename_status_parking_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='resevation_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
