# Generated by Django 4.1.2 on 2022-10-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_reservation_date_alter_reservation_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='parking.parking'),
        ),
    ]
