# Generated by Django 4.1.2 on 2022-11-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_parking_name_alter_parking_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='time_from',
            new_name='checkin',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='time_to',
            new_name='checkout',
        ),
        migrations.AlterField(
            model_name='parking',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
